import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/redux/provider/Provider";
import { UserProvider } from "@auth0/nextjs-auth0/client";
// import { trcp } from "../lib/trpc";
// import Provider from "@/lib/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <UserProvider>
        <html lang="en">
          <body className={inter.className}>
            {/* <Provider> */}
              {children}
            {/* </Provider> */}
          </body>
        </html>
      </UserProvider>
    </Providers>
  );
}
